<?php
/*
AUTHOR:- RITHUNAND [BENCHAMXD]
CHANNEL:- @INDUSBOTS 
THIS REPO IS LICENCED WITH GENERAL PUBLIC LICENSE VERSION:3.0
(c) RITHUNAND K
*/
$TG_BOT_TOKEN = $_ENV['6145802775:AAEN3CASHzonhpE5HIivs0cTut5tIxiJdnU'];
$BOT_NAME = $_ENV['Pix AI'];
$BOT_USERNAME = $_ENV['pix_ai_bot'];

?>
